sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  slack: norch:wLsHiXjnAH5BdtTq3qtAqGp7
  email: true
node_js:
  - '10'
  - '8'
  - '6'
  - '4'
before_script:
  - npm prune
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
