name: test
on: [push]
jobs:
  install-fii:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run test-node
      - run: npm run build
        
