name: tests
on:
  - pull_request
  - push
jobs:
  run-tests:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [20, 22, 24, 25, 26]
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test
        timeout-minutes: 5 # If the tests fails, the browser will hang open indefinitely
